# Generated by Django 2.0.6 on 2018-07-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='other',
            field=models.CharField(blank=True, help_text='Slack:@username', max_length=256, null=True, verbose_name='Other'),
        ),
    ]
