version: '3'
services:
  db:
    environment:
      POSTGRES_USER: rcrm
      POSTGRES_PASSWORD: secret
  backend:
    command: python manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
