"""
Django settings for rcrm project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import json
import os

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env_path = os.path.join(BASE_DIR, '..', '.rcrm_env.json')
if not os.path.exists(env_path):
    env_path = os.path.join(BASE_DIR, 'conf', 'env.json')
with open(env_path, 'r') as env_file:
    env = json.loads(env_file.read())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env['DEBUG']

ALLOWED_HOSTS = env['ALLOWED_HOSTS']


# Application definition

INSTALLED_APPS = [
    'rcrm_account.apps.SuitConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'rcrm',
    'rcrm_account',
    'rcrm_client',
    'rcrm_contact',
    'rcrm_dashboard',
    'rcrm_dynamic',
    'rcrm_employee',
    'rcrm_job',
    'rcrm_util',

    # Third Party Apps
    'ckeditor',
    'django_cleanup',
    'import_export',
    'location_field.apps.DefaultConfig',
    'celery'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rcrm_account.utils.LocaleMiddleware',
]

ROOT_URLCONF = 'rcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (os.path.join(BASE_DIR, 'templates'),),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rcrm_account.context_processors.context_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'rcrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = env['DATABASES']


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

SITE_ID = 1

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_CODE = 'en'
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]
LANGUAGES = [
    ('en', "English"),
    ('de', "Deutsch"),
    ('tr', "Türkçe")
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

# STATIC
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'frontend', 'static'),)
STATIC_ROOT = env['STATIC_ROOT']

# Email Settings
EMAIL_BACKEND = env['EMAIL_BACKEND']
EMAIL_HOST = env['EMAIL_HOST']
EMAIL_PORT = env['EMAIL_PORT']
EMAIL_HOST_USER = env['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = env['EMAIL_HOST_PASSWORD']
EMAIL_USE_TLS = env['EMAIL_USE_TLS']

# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = env['MEDIA_ROOT']

# User
AUTH_USER_MODEL = 'rcrm_account.User'

# CKEDITOR
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
    },
}

# Celery
CELERY_BROKER_URL = env['CELERY_BROKER_URL']
CELERY_RESULT_BACKEND = env['CELERY_RESULT_BACKEND']
