# Generated by Django 2.0.6 on 2018-06-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rcrm_utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='Position/Title')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Short Description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('address', models.ManyToManyField(to='rcrm_utils.Address')),
                ('email', models.ManyToManyField(to='rcrm_utils.Email')),
                ('phone', models.ManyToManyField(to='rcrm_utils.Phone')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rcrm_utils.SocialProfile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
