# Generated by Django 2.0.6 on 2018-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted?'),
        ),
    ]
