# Generated by Django 2.0.6 on 2018-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0003_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contact_dynamic/file/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_dynamic/image/', verbose_name='Image'),
        ),
    ]
