# Generated by Django 2.0.6 on 2018-07-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0004_auto_20180713_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Dynamic',
        ),
    ]
