# Generated by Django 2.0.6 on 2018-06-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rcrm_utils', '0001_initial'),
        ('rcrm_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Account Name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Short Description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('contact', models.ManyToManyField(to='rcrm_contact.Contact')),
                ('email', models.ManyToManyField(to='rcrm_utils.Email')),
                ('phone', models.ManyToManyField(to='rcrm_utils.Phone')),
            ],
        ),
    ]
