# Generated by Django 2.0.6 on 2018-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('tr', 'Turkish')], default='en', max_length=2),
        ),
    ]
