# Generated by Django 2.0.6 on 2018-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0002_auto_20180706_1032'),
        ('rcrm_account', '0002_user_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='CRMAccount',
        ),
        migrations.RenameModel(
            old_name='AccountRequest',
            new_name='CRMAccountRequest',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('tr', 'Türkçe')], default='en', max_length=2),
        ),
    ]
