# Generated by Django 2.0.6 on 2018-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_account', '0003_auto_20180712_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmaccount',
            options={'ordering': ('name',), 'verbose_name': 'CRM Account'},
        ),
        migrations.AlterModelOptions(
            name='crmaccountrequest',
            options={'ordering': ('account__name', 'user__email'), 'verbose_name': 'CRM Account Request'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='crmaccount',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='crmaccount',
            name='company_phone',
        ),
        migrations.AddField(
            model_name='crmaccount',
            name='email',
            field=models.EmailField(default='info@turkcell.com.tr', max_length=2014, verbose_name='RCRM Account Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crmaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='RCRM Account Phone Number'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='RCRM Description'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='RCRM Logo'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='name',
            field=models.CharField(max_length=64, verbose_name='RCRM Account Name'),
        ),
    ]
