# Generated by Django 2.0.6 on 2018-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_account', '0004_auto_20180712_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmaccountrequest',
            options={'ordering': ('account__name', 'user__first_name'), 'verbose_name': 'CRM Account Request'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='email',
            field=models.EmailField(max_length=2014, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='crmaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
