# Generated by Django 2.0.6 on 2018-07-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0004_auto_20180713_0803'),
        ('rcrm_dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleanmodel',
            options={'ordering': ('name',), 'verbose_name': 'Boolean'},
        ),
        migrations.AlterModelOptions(
            name='charfieldmodel',
            options={'ordering': ('name',), 'verbose_name': 'Charfield'},
        ),
        migrations.AlterModelOptions(
            name='datemodel',
            options={'ordering': ('name',), 'verbose_name': 'Date'},
        ),
        migrations.AlterModelOptions(
            name='datetimemodel',
            options={'ordering': ('name',), 'verbose_name': 'Date Time'},
        ),
        migrations.AlterModelOptions(
            name='dynamic',
            options={'ordering': ('name',), 'verbose_name': '*Dynamic'},
        ),
        migrations.AlterModelOptions(
            name='filemodel',
            options={'ordering': ('name',), 'verbose_name': 'File'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ('name',), 'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='textboxmodel',
            options={'ordering': ('name',), 'verbose_name': 'Text Box'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'ordering': ('name',), 'verbose_name': 'Time'},
        ),
        migrations.AlterModelOptions(
            name='urlmodel',
            options={'ordering': ('name',), 'verbose_name': 'URL'},
        ),
        migrations.AddField(
            model_name='dynamic',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_app_contact', to='rcrm_contact.Contact'),
            preserve_default=False,
        ),
    ]
