# Generated by Django 2.0.6 on 2018-07-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_dynamic', '0002_auto_20180713_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='single_line_text',
            new_name='charfield',
        ),
    ]
