# Generated by Django 2.0.6 on 2018-07-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_contact', '0001_initial'),
        ('rcrm_dynamic', '0002_auto_20180716_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dynamic',
            unique_together={('tab', 'contact')},
        ),
    ]
