# Generated by Django 2.0.6 on 2018-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(default='University Degree', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default='5 Years', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job/'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default='English', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default='Short', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='talent',
            field=models.CharField(default='talent', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='type_of_employment',
            field=models.CharField(choices=[('F', 'Full-Time'), ('P', 'Part-Time'), ('B', 'Both')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
