# Generated by Django 2.0.6 on 2018-07-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_account',
            new_name='account',
        ),
    ]
