# Generated by Django 2.0.6 on 2018-07-18 08:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcrm_job', '0002_auto_20180717_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1024),
        ),
    ]
